#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : filelock
Version  : 3.0.4
Release  : 1
URL      : https://github.com/benediktschmitt/py-filelock/archive/v3.0.4.tar.gz
Source0  : https://github.com/benediktschmitt/py-filelock/archive/v3.0.4.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Public-Domain
Requires: filelock-license = %{version}-%{release}
Requires: filelock-python = %{version}-%{release}
Requires: filelock-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
py-filelock
===========
`Similar Libraries <#similar-libraries>`_
~ `Installation <#installation>`_
~ `Documentation <#documentation>`_
~ `Contributions <#contributions>`_
~ `License <#license>`_

%package license
Summary: license components for the filelock package.
Group: Default

%description license
license components for the filelock package.


%package python
Summary: python components for the filelock package.
Group: Default
Requires: filelock-python3 = %{version}-%{release}

%description python
python components for the filelock package.


%package python3
Summary: python3 components for the filelock package.
Group: Default
Requires: python3-core

%description python3
python3 components for the filelock package.


%prep
%setup -q -n py-filelock-3.0.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1539722405
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/filelock
cp LICENSE.rst %{buildroot}/usr/share/package-licenses/filelock/LICENSE.rst
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/filelock/LICENSE.rst

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
